In [1]:
import json
import pandas as pd
from statistics import mean

In [2]:
TARGET = [1, 2, 3, 4, 5, 20, 39, 40, 42, 69, 70, 71, 73, 74, 75, 77, 79, 80, 81, 83, 84, 87, 90, 96, 120, 121, 122, 126, 128, 199, 200, 203, 204, 214, 259, 260, 281, 284, 291]

In [7]:
res = []
for target in TARGET:
    path = f"../tsv/first-match-scatter/{target}/cls-result.json"
    with open(path, 'r') as f:
        results = json.load(f)
    json_result = []
    logc = 0
    avgc = 0
    gndc = 0
    for r in results:
        label = r['label']
        if label == 1:
            index = 0
        else:
            index = 1
        logits = r['logits_softmax'][0][index]
        #logits = mean([i[index] for i in r['logits_softmax']])
        avg = r['avg_softmax'][index]
        gnd = r['grand_softmax'][index]
        json_result.append({
            'label': label,
            'logits': logits>0.5,
            'avg': avg>0.5,
            'gnd': gnd>0.5
        })
        if logits > 0.5:
            logc += 1
        if avg > 0.5:
            avgc += 1
        if gnd > 0.5:
            gndc += 1
    res.append([logc/len(results), avgc/len(results), gndc/len(results)])

In [8]:
pd.DataFrame(res)

           0         1         2
0   0.499121  0.446397  0.446397
1   0.465517  0.457854  0.457854
2   0.473214  0.467262  0.467262
3   0.724057  0.712264  0.712264
4   0.541516  0.509025  0.509025
5   0.495310  0.485929  0.485929
6   0.663683  0.645780  0.645780
7   0.482942  0.482942  0.482942
8   0.573620  0.582822  0.582822
9   0.545455  0.520751  0.520751
10  0.660229  0.565480  0.565480
11  0.470333  0.470333  0.470333
12  0.519685  0.519685  0.519685
13  0.466042  0.466042  0.466042
14  0.461009  0.461009  0.461009
15  0.500000  0.488506  0.488506
16  0.501408  0.481690  0.481690
17  0.501558  0.492212  0.492212
18  0.673973  0.750685  0.750685
19  0.471223  0.417266  0.417266
20  0.599190  0.611336  0.611336
21  0.614035  0.530702  0.530702
22  0.437500  0.437500  0.437500
23  0.671233  0.735160  0.735160
24  0.675182  0.697080  0.697080
25  0.565365  0.568761  0.567063
26  0.484018  0.481735  0.481735
27  0.505747  0.505747  0.505747
28  0.492063  0.492063  0.492063
29  0.559896  0.536458  0.536458
30  0.419890  0.414365  0.414365
31  0.901408  0.896714  0.896714
32  0.852535  0.861751  0.861751
33  0.641221  0.625954  0.625954
34  0.513333  0.482222  0.482222
35  0.558242  0.494505  0.494505
36  0.528536  0.486352  0.486352
37  0.475177  0.470449  0.470449
38  0.470075  0.470698  0.470698

In [9]:
res2 = []
for target in TARGET:
    path = f"../tsv/first-match-scatter/{target}/cls-result-2.json"
    with open(path, 'r') as f:
        results = json.load(f)
    json_result = []
    logc = 0
    avgc = 0
    gndc = 0
    for r in results:
        label = r['label']
        if label == 1:
            index = 0
        else:
            index = 1
        logits = r['logits_softmax'][0][index]
        #logits = mean([i[index] for i in r['logits_softmax']])
        avg = r['avg_softmax'][index]
        gnd = r['grand_softmax'][index]
        json_result.append({
            'label': label,
            'logits': logits>0.5,
            'avg': avg>0.5,
            'gnd': gnd>0.5
        })
        if logits > 0.5:
            logc += 1
        if avg > 0.5:
            avgc += 1
        if gnd > 0.5:
            gndc += 1
    res2.append([logc/len(results), avgc/len(results), gndc/len(results)])

In [10]:
pd.DataFrame(res2)

           0         1         2
0   0.499121  0.446397  0.460457
1   0.465517  0.457854  0.498084
2   0.473214  0.467262  0.497024
3   0.724057  0.712264  0.523585
4   0.541516  0.509025  0.516245
5   0.495310  0.485929  0.499062
6   0.663683  0.645780  0.482097
7   0.482942  0.482942  0.504264
8   0.573620  0.582822  0.500000
9   0.545455  0.520751  0.508893
10  0.660229  0.565480  0.493060
11  0.470333  0.470333  0.544139
12  0.519685  0.519685  0.513780
13  0.466042  0.466042  0.512881
14  0.461009  0.461009  0.557339
15  0.500000  0.488506  0.505747
16  0.501408  0.481690  0.467606
17  0.501558  0.492212  0.514019
18  0.673973  0.750685  0.473973
19  0.471223  0.417266  0.532374
20  0.599190  0.611336  0.481781
21  0.614035  0.530702  0.583333
22  0.437500  0.437500  0.524038
23  0.671233  0.735160  0.538813
24  0.675182  0.697080  0.481752
25  0.565365  0.568761  0.536503
26  0.484018  0.481735  0.505708
27  0.505747  0.505747  0.475096
28  0.492063  0.492063  0.539683
29  0.559896  0.536458  0.520833
30  0.419890  0.414365  0.524862
31  0.901408  0.896714  0.431925
32  0.852535  0.861751  0.442396
33  0.641221  0.625954  0.484733
34  0.513333  0.482222  0.466667
35  0.558242  0.494505  0.479121
36  0.528536  0.486352  0.503722
37  0.475177  0.470449  0.470449
38  0.470075  0.470698  0.478803